version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
       - MYSQL_DATABASE=db
  web:
    build:
      context: ./
      dockerfile: ./config/docker/web/Dockerfile
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=docker.env
    volumes:
      - ./app/website:/var/www/html/:rw
      - ./app/:/var/www/html/:rw
      - ./config/docker/web/rewrite.conf:/etc/apache2/conf-enabled/rewrite.conf
